spring:
  application:
    name: ec-webapp

  datasource:
    url: jdbc:h2:mem:ecdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

logging:
  level:
    com.example.ec: DEBUG
    org.springframework.web: INFO
